Update 通用设备编译固件.yml

diff --git a/.github/workflows/通用设备编译固件.yml b/.github/workflows/通用设备编译固件.yml
--- a/.github/workflows/通用设备编译固件.yml
+++ b/.github/workflows/通用设备编译固件.yml
@@ -126,6 +126,12 @@ jobs:
           find dl -size -1024c -exec ls -l {} \;
           find dl -size -1024c -exec rm -f {} \;
 
+      - name: Disable Werror
+        run: |
+          sed -i 's/CONFIG_WERROR=y/CONFIG_WERROR=n/' .config || true
+          echo "CONFIG_WERROR=n" >> .config
+          make defconfig
+
       - name: Compile the OpenWrt
         id: compile
         run: |
